name: Go
on: [push, pull_request]
jobs:
  build:
    name: Checks & Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Format
      uses: sjkaliski/go-github-actions/fmt@v0.5.0
      env:
        GO_IGNORE_DIRS: "./vendor"

    - name: Lint
      uses: sjkaliski/go-github-actions/lint@v0.5.0
      env:
        GO_LINT_PATHS: "./gandi/..."

    # Disable the TF Provider Lint action until https://github.com/bflad/tfproviderlint-github-action/pull/1 is fixed
    # - name: TF Provider Lint
    #   uses: bflad/tfproviderlint-github-action@master
    #   with:
    #     args: "./..."

    - name: Build
      run: |
        make
        go_version=$(go version)
        os_arch=${go_version##*\ }
        mv terraform-provider-gandi terraform-provider-gandi-${os_arch%%\/*}_${os_arch##*\/}
        ls -la terraform-provider-gandi*

    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: terraform-provider-gandi*
  deploy:
    name: Push artifact to Github release
    if: github.event_name == 'push' && contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: build-artifact
    - name: Upload binaries to github release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build-artifact/terraform-provider-gandi*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
